name: Build on MacOS (Test)

on:
  workflow_dispatch:
    inputs:
      refspec:
        description: "Github ref-spec of the reference to build"
        required: true
        type: string
      version:
        description: "The resulting version number of the build"
        required: true
        type: string
      timestamp:
        description: "The timestamp of the version"
        required: true
        type: number

env:
  target_dir: "${{ github.workspace }}/BUILD_RESULTS/MacOS"

jobs:
  build:
    name: Build and test MacOS
    runs-on: macos-12
    steps:
    - name: "Checkout source"
      uses: actions/checkout@v3
      with:
        repository: bareos/bareos
        ref: "${{ inputs.refspec }}"
    - name: Install dependencies
      run: |
        brew install jansson
    - name: Inject version parameters
      run: |
        echo -e "set(VERSION_STRING \"$VERSION\")\nset(VERSION_TIMESTAMP \"$TIMESTAMP\")" >core/cmake/BareosVersion.cmake
        cat core/cmake/BareosVersion.cmake
      env:
        VERSION: "${{ inputs.version }}"
        TIMESTAMP: "${{ inputs.timestamp }}"
    - name: Build package
      run: |
        cmake -S . -B cmake-build -Dclient-only=yes
        cmake --build cmake-build -- package
        ls -la ./*.pkg
        mkdir -p "${{ env.target_dir }}"
        mv ./*.pkg "${{ env.target_dir }}"
      env:
        CFLAGS: -I/usr/local/include
        CXXFLAGS: -I/usr/local/include

