name: Build MacOS packages
run-name: "${{ inputs.run-name }}"

on:
  workflow_dispatch:
    inputs:
      version:
        description: "The resulting version number of the build"
        required: true
        type: string
      timestamp:
        description: "The timestamp of the version"
        required: true
        type: number
      repository:
        description: "The repository to retrieve the sources from"
        required: false
        type: string
      ref:
        description: "The ref in the repository to checkout"
        required: false
        type: string
      treeid:
        description: "The tree-id that the checkout should have"
        required: false
        type: string
      run-name:
        description: "The workflow run's name"
        required: false
        type: string
      ssh_access:
        description: 'Enable sshd debugging'
        type: boolean
        required: false
        default: false

env:
  artifact_dir: "${{ github.workspace }}/artifacts"

jobs:
  build:
    name: Build MacOS packages
    runs-on: macos-13
    steps:
    - name: "Checkout source"
      uses: actions/checkout@v4
    - name: Build package
      run: |
        find . -ls
      env:
        CFLAGS: -I/usr/local/include
        CXXFLAGS: -I/usr/local/include
        CMAKE_BUILD_PARALLEL_LEVEL: 4
