name: Build MacOS packages
run-name: "${{ inputs.run-name }}"

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      ref:
        description: "The ref in the repository to checkout"
        required: false
        type: string

env:
  artifact_dir: "${{ github.workspace }}/artifacts"

jobs:
  build:
    name: Build MacOS packages
    runs-on: macos-13
    steps:
    - name: "Checkout source"
      uses: actions/checkout@v4
    - name: Build package
      run: |
        find . -ls
        cmake -S . -B build
        cmake --build build
      env:
        CFLAGS: -I/usr/local/include
        CXXFLAGS: -I/usr/local/include
        CMAKE_BUILD_PARALLEL_LEVEL: 4
