---
name: Close Pull Request

# only trigger on pull request closed events
on:
  pull_request_target:
    types: [ closed ]
    branches:
      - master
      - bareos-[2-9]*

jobs:
  merge_job:
    # this job will only run if the PR has been closed without being merged
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.base_ref }}

    - uses: arogge/changelog-action@v2
      with:
        pull-request: ${{ github.event.number }}
        change-entry: "${{ github.event.pull_request.title }}"

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update CHANGELOG.md
        file_pattern: CHANGELOG.md
        branch: ${{ github.base_ref }}
        commit_author: ""
        commit_user_name: "Changelog Bot"
        commit_user_email: "<changelog-bot@bareos.com>"
